name: build

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Version tag name'
        required: true
        default: '8.0.0'

jobs:
  build:
    name: Build Jar
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '8'

      - name: Build Jar
        run: bash crack.sh ${{ github.event.inputs.tag_name }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Build Jar
        run: pwd && ls ./output
      - name: Upload Jar
        uses: actions/download-artifact@v4
        with:
          path: output
      - name: Upload Jar to GitHub Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: output/*.jar
          generateReleaseNotes: true
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.event.inputs.tag_name }}
          body: |
              This release includes:
              - Built Jar on GitHub Actions.
