name: build

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Version tag name'
        required: true
        default: '8.0.0'

jobs:
  build:
    name: Build Jar
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '8'

      - name: Build Jar
        run: bash crack.sh ${{ github.event.inputs.tag_name }} && pwd && ls "`pwd`"

      - name: Upload Jar
        uses: actions/download-artifact@v4
        with:
          name: x-pack-core-${{ github.event.inputs.tag_name }}
          path: ./output/*.jar
          
      - name: Upload Jar to GitHub Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: ./output/*.jar
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.event.inputs.tag_name }}
          body: |
              This release includes:
              - Built Jar on GitHub Actions.
