name: build

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Version Tag Name'
        required: true
        default: '8.0.0'
      jdk_ver:
        description: 'Version Jdk'

jobs:
  build:
    name: Build Jar
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set JDK version based on ES version
        run: |
          JDK_VER="${{ github.event.inputs.jdk_ver }}"
          if [ -z "$JDK_VER" ]; then
            ES_VERSION="${{ github.event.inputs.tag_name }}"
            # Determine JDK version based on Elasticsearch version
            if [[ "$(echo $ES_VERSION | cut -d'.' -f1)" -ge 8 ]]; then
              echo "Using JDK 20 for Elasticsearch version $ES_VERSION (>= 7.x)"
              echo "JAVA_VERSION=20" >> $GITHUB_ENV
            elif [[ "$(echo $ES_VERSION | cut -d'.' -f1)" -lt 7 ]]; then
              echo "Using JDK 1.8 for Elasticsearch version $ES_VERSION (< 7.x)"
              echo "JAVA_VERSION=8" >> $GITHUB_ENV
            else
              echo "Using JDK 11 for Elasticsearch version $ES_VERSION (<= 7.x)"
              echo "JAVA_VERSION=11" >> $GITHUB_ENV
            fi
          else
            echo "JAVA_VERSION=$JDK_VER" >> $GITHUB_ENV
          fi
          
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: ${{ env.JAVA_VERSION }}

      - name: Build Jar
        run: bash crack.sh ${{ github.event.inputs.tag_name }} && pwd && ls "`pwd`"

      - name: Upload Jar
        uses: actions/upload-artifact@v4
        with:
          name: x-pack-core-${{ github.event.inputs.tag_name }}
          path: ./output/*.jar
          
      - name: Upload Jar to GitHub Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: ./output/*.jar
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.event.inputs.tag_name }}
          body: |
              This release includes:
              - Built Jar on GitHub Actions.
